### ISSUE TITLE
can not load "mesh" from "XXX.h5" file 

### ISSUE THREAD

**Issue by mingxingdou** [uos/pluto_robot#9]
### when i run "roslaunch pluto_navigation botanical_garden_osnabrueck.launch",  there was an error as follows. Has anyone encountered this problem when running this package? How to solve this problem? Thanks!
**[ INFO] [1671008756.959023813]: Load "mesh" from file "/XXX/botanical_garden_osnabrueck.h5"...
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139961031705856:
  #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1208 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 273 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
terminate called after throwing an instance of 'HighFive::FileException'
  what():  Unable to open file /home/XXX/botanical_garden_osnabrueck.h5 (File accessibilty) Not an HDF5 file
Traceback (most recent call last):
  File "/home/dmx/pluto_robot_ws/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py", line 3, in <module>
    import rospy
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in <module>
    import roslib
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest  # noqa: F401
  File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ModuleNotFoundError: No module named 'rospkg'
[navigation_smach-3] process has died [pid 4740, exit code 1, cmd /home/dmx/pluto_robot_ws/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py __name:=navigation_smach __log:=/home/dmx/.ros/log/84662c86-7b8e-11ed-83be-548d5a88c769/navigation_smach-3.log].
log file: /home/dmx/.ros/log/84662c86-7b8e-11ed-83be-548d5a88c769/navigation_smach-3*.log
[ERROR] [1671008757.996984996]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
**

**Comment by graiola** [comment]
same problem here

**Comment by Quest2GM** [comment]
Yup same problem with me as well. @spuetz, @mklpiening  do you have a solution to this? Thanks!

My output log is slightly different, but similar problem overall:

Traceback (most recent call last):
  File "/home/sinarasi/Documents/cws_yuhan/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py", line 5, in <module>
    import smach_ros
  File "/opt/ros/melodic/lib/python2.7/dist-packages/smach_ros/__init__.py", line 52, in <module>
    from util import set_preempt_handler
ModuleNotFoundError: No module named 'util'
[ INFO] [1671749082.106186257, 37.272000000]: mesh file is set to: /home/sinarasi/Documents/cws_yuhan/src/pluto_robot/pluto_navigation/maps/botanical_garden_osnabrueck/botanical_garden_osnabrueck.h5
[ INFO] [1671749082.111533830, 37.277000000]: Dynamic reconfigure callback...
[ INFO] [1671749082.116399973, 37.282000000]: Reading map file...
[ INFO] [1671749082.116417461, 37.282000000]: server url: 
[ INFO] [1671749082.116426165, 37.282000000]: Load "mesh" from file "/home/sinarasi/Documents/cws_yuhan/src/pluto_robot/pluto_navigation/maps/botanical_garden_osnabrueck/botanical_garden_osnabrueck.h5"...
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 140076577858816:
  #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1208 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 273 in H5F__super_read(): file signature not found
    major: File accessibilty
    minor: Not an HDF5 file
terminate called after throwing an instance of 'HighFive::FileException'
  what():  Unable to open file /home/sinarasi/Documents/cws_yuhan/src/pluto_robot/pluto_navigation/maps/botanical_garden_osnabrueck/botanical_garden_osnabrueck.h5 (File accessibilty) Not an HDF5 file
[ERROR] [1671749082.219345912, 37.387000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.219427871, 37.387000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.222609390, 37.390000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.222635919, 37.390000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.226992807, 37.395000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.227017792, 37.395000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[ERROR] [1671749082.227035766, 37.395000000]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?)
[navigation_smach-2] process has died [pid 22172, exit code 1, cmd /home/sinarasi/Documents/cws_yuhan/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py __name:=navigation_smach __log:=/home/sinarasi/.ros/log/22115aca-824a-11ed-9ffd-0242c4426dcc/navigation_smach-2.log].
log file: /home/sinarasi/.ros/log/22115aca-824a-11ed-9ffd-0242c4426dcc/navigation_smach-2*.log
[move_base_flex-1] process has died [pid 22171, exit code -6, cmd /opt/ros/melodic/lib/mbf_mesh_nav/mbf_mesh_nav __name:=move_base_flex __log:=/home/sinarasi/.ros/log/22115aca-824a-11ed-9ffd-0242c4426dcc/move_base_flex-1.log].
log file: /home/sinarasi/.ros/log/22115aca-824a-11ed-9ffd-0242c4426dcc/move_base_flex-1*.log

**Comment by USTCerzmj** [comment]
same problem

**Comment by USTCerzmj** [comment]
> ### when i run "roslaunch pluto_navigation botanical_garden_osnabrueck.launch", there was an error as follows. Has anyone encountered this problem when running this package? How to solve this problem? Thanks!
> 
> *_[ INFO] [1671008756.959023813]: Load "mesh" from file "/XXX/botanical_garden_osnabrueck.h5"... HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139961031705856: #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file major: File accessibilty minor: Unable to open file #1: ../../../src/H5Fint.c line 1208 in H5F_open(): unable to read superblock major: File accessibilty minor: Read failed #2: ../../../src/H5Fsuper.c line 273 in H5F__super_read(): file signature not found major: File accessibilty minor: Not an HDF5 file terminate called after throwing an instance of 'HighFive::FileException' what(): Unable to open file /home/XXX/botanical_garden_osnabrueck.h5 (File accessibilty) Not an HDF5 file Traceback (most recent call last): File "/home/dmx/pluto_robot_ws/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py", line 3, in import rospy File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/**init**.py", line 49, in from .client import spin, myargv, init_node, File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 52, in import roslib File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/**init**.py", line 50, in from roslib.launcher import load_manifest # noqa: F401 File "/opt/ros/melodic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in import rospkg ModuleNotFoundError: No module named 'rospkg' [navigation_smach-3] process has died [pid 4740, exit code 1, cmd /home/dmx/pluto_robot_ws/src/pluto_robot/pluto_navigation/scripts/navigation_sm.py __name:=navigation_smach __log:=/home/dmx/.ros/log/84662c86-7b8e-11ed-83be-548d5a88c769/navigation_smach-3.log]. log file: /home/dmx/.ros/log/84662c86-7b8e-11ed-83be-548d5a88c769/navigation_smach-3_.log [ERROR] [1671008757.996984996]: Mesh display: no visual available, can't draw mesh! (maybe no data has been received yet?) **

@Quest2GM @mingxingdou @graiola Hi bro,I have resolved this issue by ensuring that Git LFS is installed. Make sure to install Git LFS before cloning this repository, and then you will be able to successfully download the mesh and load it."
